baseURL = "/"
languageCode = "it"
title = "Giorgio Loi"
theme = "personal-web"
copyright="Â© Giorgio Loi - 2020"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Giorgio Loi"
  sub = "Benvenuti nel mio sito"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['blog'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.jpg" # checkout https://gopherize.me/
  h1 = 'Ops!'
  p = "Sembra che questa pagina non esista."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "post"
  servizi = "project"

[params.sidebar]
  backgroundImage = "/images/susirboniv.jpg" # header background image -
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/profilolink.jpg" # - default "/images/profilolink.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/Gioxor"
  linkedin = "https://www.linkedin.com/in/giorgioloi/"
  facebook = "https://www.facebook.com/giorgio.loi1"
  youtube = "https://www.youtube.com/c/GiorgioLoiyo"
  instagram = "https://www.instagram.com/gioxor/"

[params.contact]
  email = "info@giorgioloi.com"
  text= "E-mail" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "Chi sono"
  title = "Chi sono"
  url = "/about/"
  weight = -130

[[menu.main]]
  identifier = "servizi"
  name = "Servizi"
  title = "Servizi"
  url = "/servizi/"
  weight = -120

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog section"
  url = "/post/"
  weight = -110

  [[menu.main]]
  identifier = "support"
  name = "Supportami"
  title = "Vuoi supportarmi?"
  url = "/support/"
  weight = -100

    [[menu.main]]
  identifier = "contact"
  name = "Contattami"
  title = "Contattami"
  url = "/contattami/"
  weight = -90

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
